### ISSUE TITLE
transcript quantification (Salmon/Kallisto) should use trimmed reads

### ISSUE THREAD

**Issue by gpertea** [LieberInstitute/SPEAQeasy#110]
Currently the input channel for TxQuantSalmon and TxQuantKallisto tx_quant_inputs is built from [untrimmed fastq](https://github.com/LieberInstitute/SPEAQeasy/blob/master/main.nf#L874-L878). 
I suggest setting that channel in a similar way to [alignment_inputs](https://github.com/LieberInstitute/SPEAQeasy/blob/master/main.nf#L1203-L1208) instead.  

Reason: it seems that RNASeq at LIBD is now using 150bp NovaSeq paired reads and many of these have the full adapter sequence left in there, which is longer than what the implicit soft-clipping in kallisto/salmon can handle. In my tests, this can lower the transcriptome mapping rate by about 25-30% on average when the untrimmed reads are used directly - so we lose transcript coverage this way.  

And since we're using rRNA depletion, we already have a low tx mapping rate (due to the abundance of intronic reads), but that rate can now dip into the 20s-30s as many untrimmed reads fail to pseudo-align.

This only impacts rse_tx, of course - gene, exon and junction counts are using the full HISAT2/STAR alignments of the trimmed reads, so the mapping rate is OK there.

**Comment by Nick-Eagles** [comment]
Ok, I can do this. Similarly, I'll make ERCC quantification (which is also just pseudoalignment) operate on trimmed reads as well.
