### ISSUE TITLE
Make code more robust

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/SPEAQeasy#67]
Hi,

While writing #66 and in particular, while checking https://github.com/LieberInstitute/SPEAQeasy/blob/master/scripts/build_annotation_objects.R#L125 I noticed that some R commands are written in such a way that they assume that the columns will always be the same. That is not necessarily the case. For example `geneMap[geneMap$type == 'gene', c(1:5, 10, 13)]` assumes that we'll always want columns 1 through 5, 10 and 13. Instead, I recommend using a character vector here. Let's say `c("seqnames", "start", "end", "width", "strand", "gene_id", "gene_name")`. We went through a similar process at https://github.com/LieberInstitute/spatialDLPFC/issues/4.

You can use the Gencode v37 and v25 output I included at #66 and check if names have changed for human versions across time. Likely they haven't in if they did, then it's also likely that column numbers changed too. With column names, we'll get an error if things changed. With numbers, we won't necessarily get an error (the columns could be of the same type) and it'll be harder to identify the source of the error.

Best,
Leo

**Comment by Nick-Eagles** [comment]
I've solved the original issue described in `build_annotation_objects.R`. However, there are a few other segments of code that are similarly fragile (hardcode indices to data that could change with time). I think this issue can be considered solved once similar changes are made [here](https://github.com/LieberInstitute/SPEAQeasy/blob/65841eef3803cc0b95e9e8256a9585e6877b7d0f/scripts/create_count_objects-human.R#L307), [here](https://github.com/LieberInstitute/SPEAQeasy/blob/65841eef3803cc0b95e9e8256a9585e6877b7d0f/scripts/create_count_objects-human.R#L106-L268) and [here](https://github.com/LieberInstitute/SPEAQeasy/blob/65841eef3803cc0b95e9e8256a9585e6877b7d0f/scripts/create_count_objects-human.R#L360-L399). In the last two links, the entire code (for parsing FastQC and HISAT2 logs) will likely have to be re-written.

**Comment by Nick-Eagles** [comment]
For the [first link from above](https://github.com/LieberInstitute/SPEAQeasy/blob/65841eef3803cc0b95e9e8256a9585e6877b7d0f/scripts/create_count_objects-human.R#L307), there doesn't appear to be an obvious way to make the code more robust (there are no colnames or labels to use when splitting the `target_id` column by the `|` delimiter). For this reason, I won't consider that code segment as part of the current issue to solve. I'll soon commit fixes for the latter two links in the above comment, and at that point I'll consider the issue resolved.
