### ISSUE TITLE
Check JHPCE config file `clusterOptions`

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/SPEAQeasy#9]
Is the current JHPCE config file well specified? https://github.com/LieberInstitute/RNAsp/blob/049679dd1dd2d2636ae54fc7c0b89c364b9a6998/conf/jhpce.config

I'm not 100% sure that we are missing `h_fsize` as stated in this commit message https://github.com/LieberInstitute/RNAsp/commit/e56c0a2bd331a865ca10109cd468617a02c66b4a. Similarly, we might have to state the `mem_free` option too. I have higher default values of `h_fsize` which might be why I didn't see this problem. In any case, it'd be great to make sure that the config file is well specified.

**Comment by gpertea** [comment]
Could (should?) the `mem_free` option as used in the CountObjects step be scaled dynamically depending on the number of samples in `samples.manifest` ?
After using a larger `mem_free` value in the `jhpce.config` file in a few small runs last week I got an email from JHPCE support (Subj: _"JHPCE Cluster Job RAM Exception Report"_) basically scolding me for wasting RAM on the cluster (I used `mf=24G` for the countObjects step as I had a larger batch to process before that; using `mf=70G` for 2 cores essentially asks for 140G RAM which would be an even bigger waste for regular size batches).

**Comment by gpertea** [comment]
I think a decent estimate for the number of reads (or total bases) in a sample can be made by looking at the input file sizes (multiply by ~3 for the compressed ones I guess). Anyway I think it would be good for now if the user can provide this as an option for a specific run, by modifying their own instance of the `run*.sh` script -- I hope nextflow allows this kind of override of values in `jhpce.config`.
